In [1]:
import pandas as pd

In [2]:
path = "data/countypres_2000-2024.csv"
df = pd.read_csv(path)

In [3]:
mid = df[(df['county_name'] == 'MIDDLESEX') & (df['state_po'] == 'NJ') & (df['year'] == 2024)]
mid

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
10182,NEW JERSEY,MIDDLESEX,2024,NJ,34023.0,US PRESIDENT,OTHER,OTHER,10042.0,365187,20260225,TOTAL
10183,NEW JERSEY,MIDDLESEX,2024,NJ,34023.0,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,884.0,365187,20260225,TOTAL
10184,NEW JERSEY,MIDDLESEX,2024,NJ,34023.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,162459.0,365187,20260225,TOTAL
10185,NEW JERSEY,MIDDLESEX,2024,NJ,34023.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,191802.0,365187,20260225,TOTAL

In [4]:
mid['candidatevotes'].sum()

np.float64(365187.0)

In [5]:
mid['share'] = (mid['candidatevotes'] / mid['totalvotes'])

/var/folders/by/8m6g8s3x5m30_ccy7fgy5xnc0000gn/T/ipykernel_3335/2337094022.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mid['share'] = (mid['candidatevotes'] / mid['totalvotes'])

In [6]:
mid

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode,share
10182,NEW JERSEY,MIDDLESEX,2024,NJ,34023.0,US PRESIDENT,OTHER,OTHER,10042.0,365187,20260225,TOTAL,0.027498
10183,NEW JERSEY,MIDDLESEX,2024,NJ,34023.0,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,884.0,365187,20260225,TOTAL,0.002421
10184,NEW JERSEY,MIDDLESEX,2024,NJ,34023.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,162459.0,365187,20260225,TOTAL,0.444865
10185,NEW JERSEY,MIDDLESEX,2024,NJ,34023.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,191802.0,365187,20260225,TOTAL,0.525216

In [7]:
df2 = pd.read_csv("data/iou_zipcodes_2024.csv")

In [8]:
df2

,zip,eiaid,utility_name,state,service_type,ownership,comm_rate,ind_rate,res_rate
0,85321,176,Ajo Improvement Co,AZ,Bundled,Investor Owned,0.114389,0.000000,0.125649
1,36560,195,Alabama Power Co,AL,Bundled,Investor Owned,0.148399,0.079544,0.167720
2,36513,195,Alabama Power Co,AL,Bundled,Investor Owned,0.148399,0.079544,0.167720
3,36280,195,Alabama Power Co,AL,Bundled,Investor Owned,0.148399,0.079544,0.167720
4,35473,195,Alabama Power Co,AL,Bundled,Investor Owned,0.148399,0.079544,0.167720
...,...,...,...,...,...,...,...,...,...
48999,96146,57483,Liberty Utilities,CA,Bundled,Investor Owned,0.259400,0.000000,0.259230
49000,96161,57483,Liberty Utilities,CA,Bundled,Investor Owned,0.259400,0.000000,0.259230
49001,96133,57483,Liberty Utilities,CA,Bundled,Investor Owned,0.259400,0.000000,0.259230
49002,96118,57483,Liberty Utilities,CA,Bundled,Investor Owned,0.259400,0.000000,0.259230
49003,96107,57483,Liberty Utilities,CA,Bundled,Investor Owned,0.259400,0.000000,0.259230

In [9]:
df2[df2['zip'] == 8854]

,zip,eiaid,utility_name,state,service_type,ownership,comm_rate,ind_rate,res_rate
37061,8854,15477,Public Service Elec & Gas Co,NJ,Bundled,Investor Owned,0.146856,0.083718,0.204170
37423,8854,15477,Public Service Elec & Gas Co,NJ,Delivery,Investor Owned,0.051143,0.050358,0.052174

In [10]:
df3 = pd.read_excel("data/ZIP_COUNTY_122025.xlsx")

In [11]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54571 entries, 0 to 54570
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ZIP                  54571 non-null  int64
 1   COUNTY               54571 non-null  int64
 2   USPS_ZIP_PREF_CITY   54571 non-null  object
 3   USPS_ZIP_PREF_STATE  54571 non-null  object
 4   RES_RATIO            54571 non-null  float64
 5   BUS_RATIO            54571 non-null  float64
 6   OTH_RATIO            54571 non-null  float64
 7   TOT_RATIO            54571 non-null  float64
dtypes: float64(4), int64(2), object(2)
memory usage: 3.3+ MB

In [12]:
df3

,ZIP,COUNTY,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
0,501,36103,HOLTSVILLE,NY,0.000000,1.000000,0.000000,1.000000
1,601,72081,ADJUNTAS,PR,0.002549,0.005051,0.012048,0.002947
2,601,72001,ADJUNTAS,PR,0.997451,0.994949,0.987952,0.997053
3,602,72117,AGUADA,PR,0.000584,0.000000,0.000000,0.000530
4,602,72005,AGUADA,PR,0.000000,0.001016,0.000000,0.000076
...,...,...,...,...,...,...,...,...
54566,99926,2198,METLAKATLA,AK,1.000000,0.000000,1.000000,1.000000
54567,99927,2198,POINT BAKER,AK,0.000000,0.000000,1.000000,1.000000
54568,99928,2130,WARD COVE,AK,0.000000,0.000000,1.000000,1.000000
54569,99929,2275,WRANGELL,AK,1.000000,1.000000,1.000000,1.000000
54570,99950,2198,KETCHIKAN,AK,1.000000,0.000000,0.000000,1.000000

In [13]:
df3[df3['ZIP'] == 8854]

,ZIP,COUNTY,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
3619,8854,34023,PISCATAWAY,NJ,0.999848,1.0,1.0,0.999902
3620,8854,34039,PISCATAWAY,NJ,0.000152,0.0,0.0,0.000098

In [14]:
df3[df3['ZIP'] == 8854]['ZIP'].astype(str).str.zfill(5)

3619    08854
3620    08854
Name: ZIP, dtype: object

In [15]:
df3.groupby("ZIP").max("RES_RATIO")

       COUNTY  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
ZIP
501     36103   0.000000   1.000000   0.000000   1.000000
601     72081   0.997451   0.994949   0.987952   0.997053
602     72117   0.999416   0.998984   1.000000   0.999395
603     72099   0.998488   0.998225   1.000000   0.998519
604     72005   1.000000   1.000000   1.000000   1.000000
...       ...        ...        ...        ...        ...
99926    2198   1.000000   0.000000   1.000000   1.000000
99927    2198   0.000000   0.000000   1.000000   1.000000
99928    2130   0.000000   0.000000   1.000000   1.000000
99929    2275   1.000000   1.000000   1.000000   1.000000
99950    2198   1.000000   0.000000   0.000000   1.000000

[39494 rows x 5 columns]